### ISSUE TITLE
Load GLTF

### ISSUE THREAD

**Issue by sunjay** [ProtoArt/spritec#1]
Want to be able to use GLTF files so we can load animations. Currently we are using OBJ files and MTL files since they were easiest. 

Instructions to help you get started:

1. Open samples/bigboi.blend in blender and export it as a gltf file. Save it in samples/bigboi.gltf
2. Use the [gltf crate](https://docs.rs/gltf) to load the exported file
3. Figure out how to extract the same info we were extracting from OBJ and MTL and feed it into the shader (you may have to adjust some types and refactor some code)
4. ???
5. Profit. (get the gltf model rendering)

**Comment by daose** [comment]
- figured out how to get indices/positions/normals and make a `geometry::Mesh` out of it
- materials are different in gltf compared to obj/mtl, considering leaving it out for now and just get something basic out
- figuring out animations would probably be later too, it would be single frame for now, seems like this part is tough

**Comment by sunjay** [comment]
Great! Do you have a branch somewhere with the code? Feel free to open a PR and we can discuss it. It's definitely good to do this in small steps. Appreciate you working on it!
