### ISSUE TITLE
Update bigboi glTF

### ISSUE THREAD

**Issue by daose** [ProtoArt/spritec#103]
### Background
Tried feeding our samples/bigboi/gltf files to [gltf-viewer](https://gltf-viewer.donmccurdy.com/) but it doesn't look right and reported errors

<img width="934" alt="image" src="https://user-images.githubusercontent.com/15278132/69479337-0d8b2880-0dca-11ea-854d-f1c4d858e8a0.png">

### Problem
Could we re-export to glTF again? Seems like they have an updated pipeline to do it (blend -> glTF) via [KhronosGruop/glTF-Blender-IO](https://github.com/KhronosGroup/glTF-Blender-IO)

// but also maybe that library could help in our possible future blender plugin

**Comment by sunjay** [comment]
I need to redo the bigboi model and animation in Blender 2.8 for this to be fully fixed. May have time to do that in a few weeks but it probably won't happen sooner unless someone picks that up from me.

**Comment by sunjay** [comment]
This will probably not happen until January. It also depends on how this affects #112. If we end up not proceeding further with glTF for the timebeing, I may put this off in favor of more pressing issues.
