### ISSUE TITLE
Parameterize Sprite Resolutions For Sprite Sheet Output

### ISSUE THREAD

**Issue by marauder00** [ProtoArt/spritec#11]
Currently we only spit out 64 by 64 models. We should try more resolutions and see how it works out.

**Comment by daose** [comment]
I've had a good experience using [clap](https://crates.io/crates/clap) for cli arguments.

**Comment by sunjay** [comment]
Yup. I'm going to do a bunch of refactoring of our prototype soon. This and several others issues are going to be part of that.
