### ISSUE TITLE
electron packaging missing dependencies

### ISSUE THREAD

**Issue by daose** [ProtoArt/spritec#200]
For some reason packaging with https://www.electron.build/ is missing dependencies (except our local spritec_binding). This means that threejs and others aren't being pulled in.

Temporary fix could be to just add them into our repo, but hopefully can figure out why this is happening. Maybe need to switch to 2 package.json layout.

**Comment by daose** [comment]
One of the file we rely on is `three/examples/js/loaders/GLTFLoader.js`, but the builder we use ignores any files within an `example` subfolder (see https://www.electron.build/configuration/contents).

> All default ignores are added in any case — you don’t need to repeat it if you configure own patterns.

Unfortunately doesn't seem like there's a way to override it https://github.com/electron-userland/electron-builder/issues/4545

Experimenting with some workarounds right now

**Comment by sunjay** [comment]
One option is to copy `GLTFLoader.js` into our source code. That's probably fine.
