### ISSUE TITLE
Support glTF Skinning for Skeletal Animation

### ISSUE THREAD

**Issue by sunjay** [ProtoArt/spritec#24]
**Update (Jan 18, 2020):** Animation work is tracked in #18. This issue is now tracking the work on supporting glTF skins. This is a big part of skeletal animation and will hopefully allow us to have a fully implemented animation engine by the time #18 is done.

Skins: https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#skins

**Comment by JLSJamesShi** [comment]
Keep this github issue in mind for edge cases:
https://github.com/KhronosGroup/glTF/issues/1275

**Comment by sunjay** [comment]
This is going to be @JLSJamesShi's main focus after the other animation issues he is assigned to have been completed. All of the animation issues are going to require a large amount of work, and this is the largest by far because of the theoretical knowledge required and the edge cases I am anticipating when we implement skinning.
