### ISSUE TITLE
Support glTF Material Properites

### ISSUE THREAD

**Issue by sunjay** [ProtoArt/spritec#27]
Related: #5 

We want to support more types of materials and various properties within them. This issue should probably be resolved through multiple small issues/PRs.

The documentation for glTF `Material`: https://docs.rs/gltf/*/gltf/struct.Material.html

In particular, the following would be really good to support:

- [ ] [Emission](https://docs.blender.org/manual/en/latest/render/cycles/nodes/types/shaders/emission.html) (via [`emissive_factor`](https://docs.rs/gltf/*/gltf/struct.Material.html#method.emissive_factor) and [`emissive_texture`](https://docs.rs/gltf/*/gltf/struct.Material.html#method.emissive_texture))
- [ ] Normal maps
- [ ] Image textures

Part of this issue is exploring the design space. What materials do we want to support? What material properties are important? How do we accomplish various affects in pixel art?

We should look at other toon shaders to see what kinds of properties they support.

**Comment by marauder00** [comment]
This is really important and I think we should complete this milestone during coop..I'm down to work on this after fixing edges.

**Comment by sunjay** [comment]
Agreed that this might be a good thing to work on after outlining. Unassigned it for now until we can figure out what our priorities are after outlining has been completed.
