### ISSUE TITLE
UX Ideas & Exploration

### ISSUE THREAD

**Issue by sunjay** [ProtoArt/spritec#38]
While #23 is about exploring GUI libraries/frameworks, this issue is specifically a place for us to brainstorm ideas about potential ways our interface could work. Feel free to comment with ideas about features we could have, what they might be useful for, and who might use this.

The CLI and configuration file are technically part of our interface, so feel free to leave ideas about that here as well.

A lot of this will be informed by the user interviews we plan to do in the future as well as the case studies (#31) we will be doing later.

**Comment by daose** [comment]
an idea for GUI:

- an empty screen divided into two
- file context menu, user can select files to open in gui
- when file opens, on the left is the 3D model, on the right is the 2D pixel art
- editing camera/animations/etc on the 3D model, the 2D pixel art should reflect "immediately"
- 2D pixel art should have a slider specifying the # of frames per second to render, the preview we show the user should look like when they import it into their game
- export button that generates the sprite sheet, with a preview auto-opening for the user

**Comment by daose** [comment]
Going to close this for more specific issues moving forward
