### ISSUE TITLE
[glTF animation] Render the first frame

### ISSUE THREAD

**Issue by daose** [ProtoArt/spritec#93]
After #71, use the two functions [`applyTransformHierarchy`](https://github.com/KhronosGroup/glTF-Sample-Viewer/blob/master/src/scene.js#L23) and [`gatherNodes`](
https://github.com/KhronosGroup/glTF-Sample-Viewer/blob/master/src/scene.js#L43) to render just the first frame.

- query animation data structure for time 0 what local transforms to apply to which node
- do applytransformhierarchy + gathernodes
- return the modified scene

**Comment by sunjay** [comment]
Closed in favor of #18
